services:
  # Spring Boot 애플리케이션
  beilsang-server:
    image: beilsang-server:stage  # 빌드된 이미지 사용
    container_name: beilsang-server
    user: "1000:1000"
    expose:
      - "8080"  # 내부 네트워크에만 노출
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SERVER_PORT=8080
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
      - KAKAO_REDIRECT_URI=${KAKAO_REDIRECT_URI}
      - KAKAO_ADMIN_KEY=${KAKAO_ADMIN_KEY}
      - KAKAO_APP_KEY=${KAKAO_APP_KEY}
      - APPLE_CLIENT_ID=${APPLE_CLIENT_ID}
      - APPLE_KEY_ID=${APPLE_KEY_ID}
      - APPLE_TEAM_ID=${APPLE_TEAM_ID}
      - APPLE_PRIVATE_KEY=${APPLE_PRIVATE_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Seoul
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    external: true
