version: '3.8'

services:
  # 애플리케이션 서비스
  beilsang-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beilsang-server
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped