spring:
  datasource: # DB
    driver-class-name: org.h2.Driver
    url: ${DB_LOCAL_URL}
    username: ${DB_LOCAL_USER}
    password:
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
