spring:
  datasource: # DB
    driver-class-name: org.postgresql.Driver
    url: ${DB_LOCAL_URL}
    username: ${DB_LOCAL_USER}
    password: ${DB_LOCAL_PASSWORD}
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
