spring:
  application:
    name: beilsang-server-v2
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local-mysql} # 배포시 github actions에서 환경변수로 stage/prod 설정
  security:
    oauth2: # OAuth
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize # 인증 uri
            token-uri: https://kauth.kakao.com/oauth/token # 토큰 요청 uri
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  cloud:
    aws:
      credentials:
        accessKey: ${AWS_ACCESS_KEY_ID}
        secretKey: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: beilsang-bucket-dev
        path:
          challenge-main: challenge/main
          challenge-cert: challenge/cert
          member-profile: member/profile


jwt:
  secret-key: ${JWT_SECRET_KEY}

# Swagger/OpenAPI 설정
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
