spring:
  application:
    name: beilsang-server-v2
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local-mysql} # 배포시 github actions에서 환경변수로 stage/prod 설정
  config:
    import:
      - classpath:nickname.yml
  servlet:
    multipart:
      max-file-size: 3MB # 파일당 최대 크기
      max-request-size: 15MB # 전체 요청 최대 크기 (여러 파일 업로드 고려)
  security:
    oauth2: # OAuth
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize # 인증 uri
            token-uri: https://kauth.kakao.com/oauth/token # 토큰 요청 uri
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  cloud:
    aws:
      credentials:
        accessKey: ${AWS_ACCESS_KEY_ID}
        secretKey: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: bs-stage-bucket
        path:
          challenge: challenge/
          member-profile: member/profile/
          feed: feed/

jwt:
  secret-key: ${JWT_SECRET_KEY}

apple:
  client-id: ${APPLE_CLIENT_ID}
  key-id: ${APPLE_KEY_ID}
  team-id: ${APPLE_TEAM_ID}
  private-key: ${APPLE_PRIVATE_KEY}

kakao:
  admin-key: ${KAKAO_ADMIN_KEY}
  app-key: ${KAKAO_APP_KEY}

# 포인트 관련 비즈니스 로직 설정
point:
  reward:
    new-member: 1000  # 신규 가입 시 지급 포인트

# 회원 관련 설정
member:
  default-profile-image: https://bs-stage-bucket.s3.ap-northeast-2.amazonaws.com/member/profile/member-profile-default.png  # S3에 업로드된 기본 프로필 이미지 URL (member-profile-default.png)

# Swagger/OpenAPI 설정
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
