server {
    listen 80;
    server_name stage.beilsang.site ; #추후 prod 배포시 추가 필요

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name stage.beilsang.site; #추후 prod 배포시 추가 필요

    ssl_certificate /etc/letsencrypt/live/stage.beilsang.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/stage.beilsang.site/privkey.pem;

    # 파일 업로드 크기 제한 (챌린지 이미지 업로드용)
    client_max_body_size 15m;

    location / {
        proxy_pass http://beilsang-server:8080; #beilsang-server는 도커 컴포즈 서비스 이름
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
