server {
    listen 80;
    server_name stage.beilsang.xyz ; #추후 prod 배포시 추가 필요

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
